version: "3.5"

services:
  db:
    image: postgres:14.2
    container_name: scrappy_web_db
    environment:
      - POSTGRES_DB=scrappy_web_test
      - POSTGRES_USER=scrappy_web
      - POSTGRES_PASSWORD=scrappy_web@pwd!
    ports:
      - "5432:5432"